# Generated by Django 4.2.7 on 2023-11-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdfName', models.CharField(max_length=120)),
                ('pdfUrl', models.URLField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('userId', models.IntegerField()),
                ('fileKey', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User')], max_length=10)),
                ('chatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload_chat.chat')),
            ],
        ),
    ]
