# Generated by Django 4.2.7 on 2023-11-03 20:25

import django.core.validators
from django.db import migrations, models
import file_upload_chat.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='fileKey',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='pdfUrl',
        ),
        migrations.AddField(
            model_name='chat',
            name='file',
            field=models.FileField(default=1, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), file_upload_chat.models.validate_file_size]),
            preserve_default=False,
        ),
    ]
