# Generated by Django 4.2.7 on 2023-11-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_chat', '0002_remove_chat_filekey_remove_chat_pdfurl_chat_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='userId',
            field=models.CharField(max_length=200),
        ),
    ]
